### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by The-Krs1** [jeeshofone/ha-apc-ecu-3#5]
Hello,

When I tried to run 'populate-configuration.py' I kept getting a 404 error. After some playing around, I changed the address from the cgi-bin to "http://10.0.0.166/index.php/realtimedata". This worked with the result: "Found 12 inverters". I copied over the JSON data and setup the shell command. I can't get things to work yet though.

If I manually run 'solarhtml2json.py' in my terminal I get this:
`Not a power data row
Not a power data row
Not a power data row
Not a power data row
Not a power data row
Not a power data row
Not a power data row
Not a power data row
Traceback (most recent call last):
  File "/dockerapps/homeassistant/config/solarhtml2json.py", line 60, in <module>
    get_power_data()
  File "/dockerapps/homeassistant/config/solarhtml2json.py", line 57, in get_power_data
    with open('www/power_data.json', 'w') as outfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'www/power_data.json'`

In Home Assistant, I'm just showing that the Shell Command ran, but nothing updates or happens.

**Comment by The-Krs1** [comment]
Update: I was able get it to run without errors, other than www/power_data.json not existing. I added that file and now it appears to work and has data in that json. I just can't seem to get Home Assistant to see that .json now.

**Comment by jeeshofone** [comment]
Hey @CayCanSafety - which model do you have? - it sounds like it may be newer than the model I'm using.

**Comment by The-Krs1** [comment]
Hey @jeeshofone . It's an ECU-3 Version 4.  I ended up getting everything to work, except there are 19 panels in the setup and this script only configures 12. I suspect because for some reason some inverters have an A and a B which doesn't work to pull data from?

![image](https://github.com/jeeshofone/ha-apc-ecu-3/assets/119623074/1c903d43-5bb1-4b21-b2a2-f0bdd0214aee)

**Comment by jeeshofone** [comment]
Ok, interesting - can you send me what the script outputs for `config_part.yaml` ?

**Comment by The-Krs1** [comment]
Sure thing:

```
rest:
  - resource: http://homeassistant.local:8123/local/power_data.json
    sensor:
      - name: "Solar Panel 01 power"
        value_template: '{{ value_json["303000003472 "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 01 grid frequency"
        value_template: '{{ value_json["303000003472 "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 01 grid voltage"
        value_template: '{{ value_json["303000003472 "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 01 temperature"
        value_template: '{{ value_json["303000003472 "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 02 power"
        value_template: '{{ value_json["303000003040 "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 02 grid frequency"
        value_template: '{{ value_json["303000003040 "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 02 grid voltage"
        value_template: '{{ value_json["303000003040 "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 02 temperature"
        value_template: '{{ value_json["303000003040 "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 03 power"
        value_template: '{{ value_json["303000003608 "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 03 grid frequency"
        value_template: '{{ value_json["303000003608 "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 03 grid voltage"
        value_template: '{{ value_json["303000003608 "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 03 temperature"
        value_template: '{{ value_json["303000003608 "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 04 power"
        value_template: '{{ value_json["303000004756 "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 04 grid frequency"
        value_template: '{{ value_json["303000004756 "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 04 grid voltage"
        value_template: '{{ value_json["303000004756 "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 04 temperature"
        value_template: '{{ value_json["303000004756 "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 05 power"
        value_template: '{{ value_json["403000317459-A "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 05 grid frequency"
        value_template: '{{ value_json["403000317459-A "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 05 grid voltage"
        value_template: '{{ value_json["403000317459-A "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 05 temperature"
        value_template: '{{ value_json["403000317459-A "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 06 power"
        value_template: '{{ value_json["403000318514-A "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 06 grid frequency"
        value_template: '{{ value_json["403000318514-A "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 06 grid voltage"
        value_template: '{{ value_json["403000318514-A "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 06 temperature"
        value_template: '{{ value_json["403000318514-A "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 07 power"
        value_template: '{{ value_json["303000004191 "][0] }}'
        device_class: power
        unit_of_measurement: "W"

      - name: "Solar Panel 07 grid frequency"
        value_template: '{{ value_json["303000004191 "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 07 grid voltage"
        value_template: '{{ value_json["303000004191 "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 07 temperature"
        value_template: '{{ value_json["303000004191 "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 08 power"
        value_template: '{{ value_json["403000317903-A "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 08 grid frequency"
        value_template: '{{ value_json["403000317903-A "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 08 grid voltage"
        value_template: '{{ value_json["403000317903-A "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 08 temperature"
        value_template: '{{ value_json["403000317903-A "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 09 power"
        value_template: '{{ value_json["403000318319-A "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 09 grid frequency"
        value_template: '{{ value_json["403000318319-A "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 09 grid voltage"
        value_template: '{{ value_json["403000318319-A "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 09 temperature"
        value_template: '{{ value_json["403000318319-A "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 10 power"
        value_template: '{{ value_json["403000318934-A "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 10 grid frequency"
        value_template: '{{ value_json["403000318934-A "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 10 grid voltage"
        value_template: '{{ value_json["403000318934-A "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 10 temperature"
        value_template: '{{ value_json["403000318934-A "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 11 power"
        value_template: '{{ value_json["403000318699-A "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 11 grid frequency"
        value_template: '{{ value_json["403000318699-A "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 11 grid voltage"
        value_template: '{{ value_json["403000318699-A "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 11 temperature"
        value_template: '{{ value_json["403000318699-A "][3] }}'
        unit_of_measurement: "°C"
        device_class: temperature

      - name: "Solar Panel 12 power"
        value_template: '{{ value_json["403000318338-A "][0] }}'
        unit_of_measurement: "W"
        device_class: power

      - name: "Solar Panel 12 grid frequency"
        value_template: '{{ value_json["403000318338-A "][1] }}'
        unit_of_measurement: "Hz"

      - name: "Solar Panel 12 grid voltage"
        value_template: '{{ value_json["403000318338-A "][2] }}'
        unit_of_measurement: "V"

      - name: "Solar Panel 12 temperature"
        value_template: '{{ value_json["403000318338-A "][3] }}'
        unit_of_measurement: "°C"
        device_class: power
```
